# Common variables for all hosts
lab_name: dicky_lab
lab_domain: dicky.lab
lab_network: 192.168.100.0/24
lab_gateway: 192.168.100.1

# DNS settings
dns_primary: 192.168.100.10
dns_secondary: 192.168.100.11
external_dns:
  - 8.8.8.8
  - 8.8.4.4

# NTP settings
ntp_servers:
  - 0.au.pool.ntp.org
  - 1.au.pool.ntp.org
  - 2.au.pool.ntp.org
  - 3.au.pool.ntp.au

# Timezone
timezone: Australia/Adelaide

# Common packages
common_packages:
  - vim
  - htop
  - curl
  - wget
  - git
  - net-tools
  - dnsutils
  - tcpdump
  - rsync
  - tmux
  - tree
  - jq
  - lsof
  - unattended-upgrades

# Security settings
ssh_port: 22
allow_password_authentication: no

# Admin user
admin_user: rdodswor
admin_groups:
  - sudo
  - adm

