---
galaxy_info:
  author: Richard Dodsworth
  description: Root Certificate Authority for Dicky Lab
  company: Dicky Lab
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - security
    - pki
    - certificates

dependencies:
  - role: common
