---
# Common role handlers

- name: restart chrony
  service:
    name: chrony
    state: restarted
  listen: restart chrony

- name: restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
  listen: restart unattended-upgrades
