---
hostname: janus
role: management

# Network configuration
interfaces:
  - name: enp0s8
    type: static
    address: 192.168.100.5/24
    gateway: 192.168.100.1
    dns:
      - 192.168.100.10      # Primary DNS (titus)
      - 192.168.100.11      # Secondary DNS (claudia)
  - name: enp0s9
    type: dhcp              # OOB management interface
    dhcp4_overrides:
      use_routes: false
      use_dns: false
    dhcp6: true
    dhcp6_overrides:
      use_routes: false
      use_dns: false

# DHCP reservation (Management, host 1)
dhcp_reservation:
  mac: "02:dc:01:01:01:01"
  ip: 192.168.100.5
  hostname: janus

dns_static_record: true

host_specific_packages:
  - ansible
  - python3-pip
  - python3-venv
