---
hostname: porta
role: gateway

# MAC addresses
interface_mac: "02:DD:04:01:01:01"  # Inside interface (primary)

# Network configuration
interfaces:
  - name: enp0s8
    type: static
    address: 192.168.100.1/24
    # No gateway - porta IS the gateway
    dns:
      - 192.168.100.10
      - 192.168.100.11
    
  - name: enp0s9
    type: dhcp
    dhcp4_overrides:
      use_dns: false
    dhcp6: true
    dhcp6_overrides:
      use_dns: false

  - name: enp0s10
    type: dhcp
    dhcp4_overrides:
      use_routes: false
      use_dns: false
    dhcp6: true
    dhcp6_overrides:
      use_routes: false
      use_dns: false

# DNS configuration
dns_static_record: true
